/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DoNFTFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "beacon"
      | "deployDoNFT"
      | "deployWrapNFT"
      | "getDoNFT"
      | "initialize"
      | "market"
      | "owner"
      | "renounceOwnership"
      | "setBeaconAndMarket"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeployDoNFT"
      | "DeployWrapERC721DualRole"
      | "Initialized"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "beacon", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deployDoNFT",
    values: [
      string,
      string,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployWrapNFT",
    values: [string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDoNFT",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "market", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBeaconAndMarket",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "beacon", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployDoNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployWrapNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDoNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "market", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBeaconAndMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DeployDoNFTEvent {
  export type InputTuple = [
    proxy: AddressLike,
    name: string,
    symbol: string,
    originalAddress: AddressLike,
    market: AddressLike,
    royaltyAdmin: AddressLike,
    gameKey: string
  ];
  export type OutputTuple = [
    proxy: string,
    name: string,
    symbol: string,
    originalAddress: string,
    market: string,
    royaltyAdmin: string,
    gameKey: string
  ];
  export interface OutputObject {
    proxy: string;
    name: string;
    symbol: string;
    originalAddress: string;
    market: string;
    royaltyAdmin: string;
    gameKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeployWrapERC721DualRoleEvent {
  export type InputTuple = [
    wrapNFT: AddressLike,
    name: string,
    symbol: string,
    originalAddress: AddressLike
  ];
  export type OutputTuple = [
    wrapNFT: string,
    name: string,
    symbol: string,
    originalAddress: string
  ];
  export interface OutputObject {
    wrapNFT: string;
    name: string;
    symbol: string;
    originalAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DoNFTFactory extends BaseContract {
  connect(runner?: ContractRunner | null): DoNFTFactory;
  waitForDeployment(): Promise<this>;

  interface: DoNFTFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  beacon: TypedContractMethod<[], [string], "view">;

  deployDoNFT: TypedContractMethod<
    [
      name: string,
      symbol: string,
      originalAddress: AddressLike,
      owner_: AddressLike,
      admin_: AddressLike,
      royaltyAdmin: AddressLike,
      gameKey: string
    ],
    [string],
    "nonpayable"
  >;

  deployWrapNFT: TypedContractMethod<
    [name: string, symbol: string, originalAddress: AddressLike],
    [string],
    "nonpayable"
  >;

  getDoNFT: TypedContractMethod<
    [nftAddress: AddressLike, gameKey: string],
    [string],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      owner_: AddressLike,
      admin_: AddressLike,
      beacon_: AddressLike,
      market_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  market: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBeaconAndMarket: TypedContractMethod<
    [beacon_: AddressLike, market_: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "beacon"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deployDoNFT"
  ): TypedContractMethod<
    [
      name: string,
      symbol: string,
      originalAddress: AddressLike,
      owner_: AddressLike,
      admin_: AddressLike,
      royaltyAdmin: AddressLike,
      gameKey: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployWrapNFT"
  ): TypedContractMethod<
    [name: string, symbol: string, originalAddress: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDoNFT"
  ): TypedContractMethod<
    [nftAddress: AddressLike, gameKey: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      owner_: AddressLike,
      admin_: AddressLike,
      beacon_: AddressLike,
      market_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "market"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBeaconAndMarket"
  ): TypedContractMethod<
    [beacon_: AddressLike, market_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DeployDoNFT"
  ): TypedContractEvent<
    DeployDoNFTEvent.InputTuple,
    DeployDoNFTEvent.OutputTuple,
    DeployDoNFTEvent.OutputObject
  >;
  getEvent(
    key: "DeployWrapERC721DualRole"
  ): TypedContractEvent<
    DeployWrapERC721DualRoleEvent.InputTuple,
    DeployWrapERC721DualRoleEvent.OutputTuple,
    DeployWrapERC721DualRoleEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DeployDoNFT(address,string,string,address,address,address,string)": TypedContractEvent<
      DeployDoNFTEvent.InputTuple,
      DeployDoNFTEvent.OutputTuple,
      DeployDoNFTEvent.OutputObject
    >;
    DeployDoNFT: TypedContractEvent<
      DeployDoNFTEvent.InputTuple,
      DeployDoNFTEvent.OutputTuple,
      DeployDoNFTEvent.OutputObject
    >;

    "DeployWrapERC721DualRole(address,string,string,address)": TypedContractEvent<
      DeployWrapERC721DualRoleEvent.InputTuple,
      DeployWrapERC721DualRoleEvent.OutputTuple,
      DeployWrapERC721DualRoleEvent.OutputObject
    >;
    DeployWrapERC721DualRole: TypedContractEvent<
      DeployWrapERC721DualRoleEvent.InputTuple,
      DeployWrapERC721DualRoleEvent.OutputTuple,
      DeployWrapERC721DualRoleEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
