/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRoyalty__factory } from "./IRoyalty__factory";
export { Royalty__factory } from "./Royalty__factory";
