/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as wrap from "./wrap";
export type { wrap };
export type { ERC4907 } from "./ERC4907";
export type { IERC4907 } from "./IERC4907";
