/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDoubleSVG,
  IDoubleSVGInterface,
} from "../../contracts/IDoubleSVG";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "type_value",
        type: "string",
      },
      {
        internalType: "uint64",
        name: "start_time",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "end_time",
        type: "uint64",
      },
    ],
    name: "genTokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDoubleSVG__factory {
  static readonly abi = _abi;
  static createInterface(): IDoubleSVGInterface {
    return new Interface(_abi) as IDoubleSVGInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDoubleSVG {
    return new Contract(address, _abi, runner) as unknown as IDoubleSVG;
  }
}
