/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWrapNFT__factory } from "./IWrapNFT__factory";
export { WrapERC721DualRole__factory } from "./WrapERC721DualRole__factory";
