/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockNftSol from "./MockNFT.sol";
export { BasicMockNFT__factory } from "./BasicMockNFT__factory";
export { MockERC20__factory } from "./MockERC20__factory";
