/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BasicMockNFT } from "./BasicMockNFT";
export type { MockERC20 } from "./MockERC20";
export type { MockNFT } from "./MockNFT";
